### ISSUE TITLE
Provide an interface such that Navigator can be extended using Lua plugins

### ISSUE THREAD

**Issue by thbonk** [thbonk/NavigatorApp#23]
As a user I want to extend Navigator with Lua plugins such that it has functions that are not part of the standard application.

Backlog Items:

- [x] https://github.com/thbonk/NavigatorApp/issues/36
- [x] https://github.com/thbonk/NavigatorApp/issues/37
- [ ] https://github.com/thbonk/NavigatorApp/issues/38
